version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: orders
        columns:
          - name: ID
            tests:
              - not_null
              - unique
      - name: customers
