version: 2

sources:
  - name: stripe
    database: dbt-tutorial
    schema: stripe
    tables:
      - name: payment
        columns:
          - name: id
            tests:
              - unique:
                  config:
                    severity: error
                    error_if: ">100"
                    warn_if: ">10"
                    where: "status = 'success'"
                    limit : 10
                    store_failures : true

                  
